sudo: required
services:
  - docker
before_install:
  - docker build -t mosleim/fe-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true mosleim/fe-test npm test
after_success:
  - docker build -t mosleim/fibo-client ./client
  - docker build -t mosleim/fibo-nginx ./nginx
  - docker build -t mosleim/fibo-server ./server
  - docker build -t mosleim/fibo-worker ./worker