sudo: required
services:
  - docker
before_install:
  - docker build -t mosleim/fe-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true mosleim/fe-test npm test
after_success:
  - docker build -t mosleim/fibo-client ./client
  - docker build -t mosleim/fibo-nginx ./nginx
  - docker build -t mosleim/fibo-server ./server
  - docker build -t mosleim/fibo-worker ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push mosleim/fibo-client
  - docker push mosleim/fibo-nginx
  - docker push mosleim/fibo-server
  - docker push mosleim/fibo-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "fibo"
  env: "fibo-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-971278214976"
  bucket_path: "fibo"
  on:
    branch: master
  access_key_id: $AWS_ID
  secret_access_key:
    secure: $AWS_KEY